name: trashvisor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  dio: ^5.5.0 # http
  path: ^1.8.3 # path
  http: ^1.1.0 # untuk mengirimkan permintaan HTTP ke APi
  flutter_dotenv: ^6.0.0 # untuk menyimpan API key dengan aman
  flutter_markdown: ^0.7.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
    - assets/images/sponsors/
    - assets/illustrations/
    - assets/bg/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700

